--------------------------------------------------------
--  File created - Monday-June-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "P1623009"."CLIENT" 
   (	"IDCLIENT" NUMBER(5,0), 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"MDP" VARCHAR2(30 BYTE), 
	"MAIL" VARCHAR2(30 BYTE), 
	"ADRESSE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "P1623009"."COMMANDE" 
   (	"IDCOMMANDE" NUMBER(10,0), 
	"NUMCOMMANDE" NUMBER(10,0), 
	"IDCLIENT" NUMBER(10,0), 
	"IDPRODUIT" NUMBER(10,0), 
	"VALIDATION" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "P1623009"."FILM" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"REALISATEUR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Table PERSONNE
--------------------------------------------------------

  CREATE TABLE "P1623009"."PERSONNE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID_PHOTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "P1623009"."PRODUIT" 
   (	"IDPRODUIT" NUMBER(10,0), 
	"NOM" VARCHAR2(30 BYTE), 
	"PRIX" NUMBER(10,2), 
	"STOCK" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "P1623009"."STAFF" 
   (	"ID_STAFF" NUMBER, 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1623009"."CLIENT_PK" ON "P1623009"."CLIENT" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1623009"."COMMANDE_PK" ON "P1623009"."COMMANDE" ("IDCOMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1623009"."FILM_PK" ON "P1623009"."FILM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Index PERSONNE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1623009"."PERSONNE_PK" ON "P1623009"."PERSONNE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1623009"."PRODUIT_PK" ON "P1623009"."PRODUIT" ("IDPRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "P1623009"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("IDCLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "1A"  ENABLE;
  ALTER TABLE "P1623009"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."CLIENT" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."CLIENT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."CLIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "P1623009"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("IDCOMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "1A"  ENABLE;
  ALTER TABLE "P1623009"."COMMANDE" MODIFY ("NUMCOMMANDE" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."COMMANDE" MODIFY ("IDCLIENT" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."COMMANDE" MODIFY ("IDPRODUIT" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."COMMANDE" MODIFY ("VALIDATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "P1623009"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A"  ENABLE;
  ALTER TABLE "P1623009"."FILM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."FILM" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."FILM" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."FILM" MODIFY ("DUREE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNE
--------------------------------------------------------

  ALTER TABLE "P1623009"."PERSONNE" ADD CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A"  ENABLE;
  ALTER TABLE "P1623009"."PERSONNE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."PERSONNE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."PERSONNE" MODIFY ("PRENOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "P1623009"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("IDPRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "1A"  ENABLE;
  ALTER TABLE "P1623009"."PRODUIT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."PRODUIT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."PRODUIT" MODIFY ("STOCK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "P1623009"."STAFF" MODIFY ("ID_STAFF" NOT NULL ENABLE);
  ALTER TABLE "P1623009"."STAFF" MODIFY ("MDP" NOT NULL ENABLE);
